include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_const_constructors
    - prefer_final_fields
    - unnecessary_this
    - use_key_in_widget_constructors
    - avoid_print             # use debugPrint() instead