// GENERATED CODE - DO NOT MODIFY BY HAND
// This file would normally be generated by:
// flutter pub run build_runner build --delete-conflicting-outputs

part of 'evidence_model.dart';

class EvidenceModelAdapter extends TypeAdapter<EvidenceModel> {
  @override
  final int typeId = 2;

  @override
  EvidenceModel read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{
      for (int i = 0; i < numOfFields; i++) reader.readByte(): reader.read(),
    };
    return EvidenceModel(
      id: fields[0] as String,
      filePath: fields[1] as String,
      type: fields[2] as EvidenceType,
      timestamp: fields[3] as DateTime,
      location: fields[4] as String,
      durationSeconds: fields[5] as int,
      smsSent: fields[6] as bool,
    );
  }

  @override
  void write(BinaryWriter writer, EvidenceModel obj) {
    writer
      ..writeByte(7)
      ..writeByte(0)
      ..write(obj.id)
      ..writeByte(1)
      ..write(obj.filePath)
      ..writeByte(2)
      ..write(obj.type)
      ..writeByte(3)
      ..write(obj.timestamp)
      ..writeByte(4)
      ..write(obj.location)
      ..writeByte(5)
      ..write(obj.durationSeconds)
      ..writeByte(6)
      ..write(obj.smsSent);
  }

  @override
  int get hashCode => typeId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EvidenceModelAdapter &&
          runtimeType == other.runtimeType &&
          typeId == other.typeId;
}

class EvidenceTypeAdapter extends TypeAdapter<EvidenceType> {
  @override
  final int typeId = 3;

  @override
  EvidenceType read(BinaryReader reader) {
    switch (reader.readByte()) {
      case 0:
        return EvidenceType.audio;
      case 1:
        return EvidenceType.video;
      default:
        return EvidenceType.audio;
    }
  }

  @override
  void write(BinaryWriter writer, EvidenceType obj) {
    switch (obj) {
      case EvidenceType.audio:
        writer.writeByte(0);
        break;
      case EvidenceType.video:
        writer.writeByte(1);
        break;
    }
  }

  @override
  int get hashCode => typeId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EvidenceTypeAdapter &&
          runtimeType == other.runtimeType &&
          typeId == other.typeId;
}
